apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: disable-networkmanager-vfs
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - contents:
            # See notes below on generating base64
            source: data:text/plain;charset=utf-8;base64,W21haW5dCnBsdWdpbnM9a2V5ZmlsZQoKW2tleWZpbGVdCnVubWFuYWdlZC1kZXZpY2VzPWludGVyZmFjZS1uYW1lOmVuczJmMnYxCg==
          mode: 420
          # Customise the name to describe the network interface being disabled
          path: /etc/NetworkManager/conf.d/50-disable-vf-interfaces.conf
