apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-bind-vfio-vf
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.4.0
    systemd:
      units:
        - name: bind-vfio-vf.service
          enabled: true
          contents: |
            [Unit]
            Description=Load vfio-pci device driver
            Requires=network-online.target create-vfs.service # Start this service only after VFs have been configured
            After=network-online.target create-vfs.service

            [Service]
            Type=oneshot
            RemainAfterExit=true
            ExecStart=/bin/bash -c 'modprobe vfio-pci'

            [Install]
            WantedBy=multi-user.target
