apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: sysctl-ip-forward
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ""
  kubeletConfig:
    allowedUnsafeSysctls:
    - "net.ipv4.ip_forward"
