apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_netdevice_ens2f2",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "10ed", "1889"],
                    "drivers": ["i40evf", "iavf", "ixgbevf"],
                    "pciAddresses": ["0000:51:11.2", "0000:51:11.3", "0000:51:11.5", "0000:51:11.7"]
                }
            },
            {
                "resourceName": "intel_sriov_netdevice_ens2f1",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "10ed", "1889"],
                    "drivers": ["i40evf", "iavf", "ixgbevf"],
                    "pciAddresses": ["0000:51:09.1", "0000:51:09.3", "0000:51:09.5", "0000:51:09.6", "0000:51:0a.0"]
                }
            }
        ]
    }
