apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-midhaul-cu
  namespace: srs72
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice_ens2f2
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "sriov-midhaul-cu-cni",
      "type": "sriov",
      "link_state": "enable",
      "ipam": {
        "type": "static",
        "addresses": [
            {
                "address": "192.168.77.1/24"
            }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-midhaul-du0
  namespace: srs72
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice_ens2f2
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "sriov-midhaul-du0-cni",
      "type": "sriov",
      "link_state": "enable",
      "ipam": {
        "type": "static",
        "addresses": [
            {
                "address": "192.168.77.2/24"
            }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-midhaul-du1
  namespace: srs72
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice_ens2f2
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "sriov-midhaul-du1-cni",
      "type": "sriov",
      "link_state": "enable",
      "ipam": {
        "type": "static",
        "addresses": [
            {
                "address": "192.168.77.3/24"
            }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-midhaul-du2
  namespace: srs72
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice_ens2f2
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "sriov-midhaul-du2-cni",
      "type": "sriov",
      "deviceID": "0000:51:11.7",
      "link_state": "enable",
      "ipam": {
        "type": "static",
        "addresses": [
            {
                "address": "192.168.77.4/24"
            }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-midhaul-du3
  namespace: srs72
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice_ens2f1
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "sriov-midhaul-du3-cni",
      "type": "sriov",
      "link_state": "enable",
      "ipam": {
        "type": "static",
        "addresses": [
            {
                "address": "192.168.77.5/24"
            }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-midhaul-du4
  namespace: srs72
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice_ens2f1
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "sriov-midhaul-du4-cni",
      "type": "sriov",
      "link_state": "enable",
      "ipam": {
        "type": "static",
        "addresses": [
            {
                "address": "192.168.77.6/24"
            }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-midhaul-du5
  namespace: srs72
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice_ens2f1
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "sriov-midhaul-du5-cni",
      "type": "sriov",
      "link_state": "enable",
      "ipam": {
        "type": "static",
        "addresses": [
            {
                "address": "192.168.77.7/24"
            }
        ]
      }
    }
